### ISSUE TITLE
trackback most recent call last

### ISSUE THREAD

**Issue by qayyumkhan15** [onepill/texture_unpacker_scirpt#6]
Hi, please help me this problem cracked my brain.

I installed Python2.7 and and Pillow-3.2.0-py2.7. Now when i run either one of the bellow command: 
C:\python27\python.exe unpacker.py atlas,
C:\python27\python.exe unpacker.py atlas plist

the below error comes,

Traceback (most recent call last):
  File "unpacker.py", line 152, in <module>
    gen_png_from_data(filename, ext)
  File "unpacker.py", line 115, in gen_png_from_data
    frames = frames_from_data(filename, ext)
  File "unpacker.py", line 29, in frames_from_data
    root = ElementTree.fromstring(open(data_filename, 'r').read())
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 101

Note: My atlas.png and atlas.plist and unpacker.py are in the same directory.

**Comment by onepill** [comment]
Hi @qayyumkhan15 , could you attach your atlas.png and atlas.plist so i could test on my end?

**Comment by qayyumkhan15** [comment]
Yes sure, here they are
[atlases.zip](https://github.com/onepill/texture_unpacker_scirpt/files/279488/atlases.zip)

And thanks for reply.. please help me about this.

**Comment by onepill** [comment]
@qayyumkhan15 

Hi, here is the result:
[atlas_ID101.zip](https://github.com/onepill/texture_unpacker_scirpt/files/279524/atlas_ID101.zip)

And it was failed due to:
1. the 2rd line in your plist file has errors, which caused the xml file couldn't be loaded by ElementTree, after i removed 2rd line, it worked
2. the files described in your plist file 
![image](https://cloud.githubusercontent.com/assets/817262/15504508/eae52f3c-21f1-11e6-93a6-327d5ebf718d.png)
dont have .png extension name, i have updated unpacker.py which now will add .png for this situation. 

So you need to update the scripts, and then remove the 2rd line of your plist file to make it a well formatted xml file, then you could unpack the png files.

**Comment by qayyumkhan15** [comment]
Thank you very much.You mean to remove the 3rd line. Just if you can discribe the 3rd line in my plist.

Thanks alot

**Comment by qayyumkhan15** [comment]
Thank you very very much.
